use_frameworks!
source 'https://github.com/nadeal/geraSpecs.git'
platform :ios, '9.0'

target 'BusBKit_Example' do
  pod 'BusBKit', :path => '../'
  pod 'YakerKit'
  target 'BusBKit_Tests' do
    inherit! :search_paths

    
  end
end
